apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kserve

components:
- ../../full/localmodel

# Exclude namespace and configmap (assumed to be pre-created)
patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kserve
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: inferenceservice-config
      namespace: kserve

