apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  name: default
  labels:
    {{- include "kserve.labels" . | nindent 4 }}
spec:
  container:
    image: {{ .Values.storageContainer.container.image }}:{{ .Values.storageContainer.container.tag }}
    imagePullPolicy: {{ .Values.storageContainer.container.imagePullPolicy }}
    name: {{ .Values.storageContainer.container.name | default "storage-initializer" }}
    resources: {{- toYaml .Values.storageContainer.container.resources | nindent 6 }}
  supportedUriFormats: {{- toYaml .Values.storageContainer.supportedUriFormats | nindent 4 }}
  workloadType: {{ .Values.storageContainer.workloadType | default "initContainer" }}
