apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kserve-localmodelnode-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kserve-localmodel-resources.labels" . | nindent 4 }}
    control-plane: "kserve-localmodelnode-agent"
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: "kserve-localmodelnode-agent"
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: "kserve-localmodelnode-agent"
        control-plane: "kserve-localmodelnode-agent"
        controller-tools.k8s.io: "1.0"
    spec:
      affinity: {{- toYaml .Values.localmodel.nodeAgent.affinity | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.localmodel.nodeAgent.image }}:{{ .Values.kserve.version | default .Values.localmodel.version | default .Values.localmodel.nodeAgent.tag }}"
        imagePullPolicy: {{ .Values.localmodel.nodeAgent.imagePullPolicy }}
        command:
        - /manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true

        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

        resources: {{- toYaml .Values.localmodel.nodeAgent.resources | nindent 10 }}
        volumeMounts:
          - mountPath: /mnt/models
            name: models
            readOnly: false

      {{- with .Values.localmodel.nodeAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      serviceAccountName: kserve-localmodelnode-agent
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml .Values.localmodel.nodeAgent.tolerations | nindent 8 }}
      volumes:
        - hostPath:
            path: /models
            type: DirectoryOrCreate
          name: models
