apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-llmisvc-controller-manager
  namespace: kserve
  labels:
    app.kubernetes.io/name: kserve-llmisvc-controller-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: kserve-llmisvc-controller-manager
