apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kserve-llmisvc-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: kserve-llmisvc-webhook-server-service.kserve.svc
  dnsNames:
  - kserve-llmisvc-webhook-server-service.kserve.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kserve-llmisvc-webhook-server-cert
